version: '2'

networks:
  test:

services:

  org_ca_ordorg:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - "9055:9055"
    command: sh -c 'fabric-ca-server start'
    volumes:
      - ../organizations/fabric-ca/ordererOrg/ca-ordererOrg:/etc/hyperledger/fabric-ca-server
    container_name: org_ca_ordorg
    networks:
      - test
  
  ca_org1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start'
    volumes:
      - ../organizations/fabric-ca/org1/org1_ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_org1
    networks:
      - test
  

  ca_org2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start'
    volumes:
      - ../organizations/fabric-ca/org2/org2_ca:/etc/hyperledger/fabric-ca-server
    container_name: ca_org2
    networks:
      - test
